services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004
    ports:
      - "5004:5004"
    networks:
      - internal_network

  app:
    build:
      context: ./frontend/src/app
      dockerfile: ../../Dockerfile  # Path to Dockerfile at project root
    depends_on:
      - api
    ports:
      - "8080:80"  # Frontend exposed on localhost:8080
    networks:
      - internal_network

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=pms_db
      - POSTGRES_USER=pms_user
      - POSTGRES_PASSWORD=pms_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pms_user", "-d", "pms_db"]
      interval: 10s
      retries: 5

volumes:
  pgdata:

networks:
  internal_network:
    driver: bridge
